name: "Federated Issue Management"
description: "Manage issues across multiple repositories in a federated manner."
author: "Michael Beemer"
branding:
  icon: "copy"
  color: "blue"

inputs:
  github-token:
    description: 'GitHub token with permissions to create and modify issues across repositories'
    required: true
  config-path:
    description: 'Path to the configuration file'
    required: false
    default: '.github/sdk-issue-sync-config.json'

runs:
  using: 'node20'
  main: 'dist/index.js'