name: "Federated Issue Management"
description: "Manage issues across multiple repositories in a federated manner."
author: "Michael Beemer"
branding:
  icon: "copy"
  color: "blue"

inputs:
  github-token:
    description: 'GitHub token with permissions to create and modify issues across repositories'
    required: true
  required-label:
    description: 'Label that must be present on the issue to trigger the action'
    required: true
    default: 'federated'
  notify-missing-permissions:
    description: 'Notifies the user if they do not have permissions to create issues in the target repository'
    required: false
    default: 'true'
  close-issues-on-parent-close:
    description: 'Close issues in the child repositories when the parent issue is closed'
    required: false
    default: 'true'
  config-path:
    description: 'Path to the configuration file'
    required: false
    default: '.github/federated-issue-action-config.json'

runs:
  using: 'node20'
  main: 'dist/index.js'