name: Federated Issue Template
description: A template for federated issue management.
labels:
  - federated

body:
  - type: markdown
    attributes:
      value: |
        This is a template for federated issue management. It will be used to create issues in multiple repositories if you have the appropriate permissions.
  - type: textarea
    attributes:
      label: Overview
      description: A brief overview of the issue.
  - type: markdown
    attributes:
      value: |
        Please add information about the issue you want to create. You can use Markdown syntax to format your text.
  - type: input
    id: sub-issue-title
    attributes:
      label: Sub-Issue Title
      description: The title of the sub-issue.
  - type: textarea
    id: sub-issue-body
    attributes:
      label: Implementation Details
      description: Details about the implementation of the issue.