name: "Dry Run Federated Issue Management"

on:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run dry run
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/dry-run-config.json