name: "Demo Federated Issue Management"

on:
  issues:
    types: [edited, closed, labeled, unlabeled]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Demo
        uses: ./
        with:
          github-token: ${{ secrets.ISSUE_MANAGEMENT_PAT }}
          config-path: .github/demo-run-config.json