name: "Dry Run Federated Issue Management"

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run dry run
        uses: ./
        with:
          github-token: ${{ secrets.ISSUE_MANAGEMENT_PAT }}
          config-path: .github/dry-run-config.json