name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build action
        run: npm run build:action
      
      - name: Check for dist/index.js changes
        run: |
          if git diff --exit-code; then
            echo "✅ build artifacts are up to date"
          else
            echo "❌ Error: build artifacts are not up to date. Please run 'npm run build' and commit the changes."
            exit 1
          fi